"""ORM models for AI nowcast history, verification, and knowledge base."""

from datetime import datetime, timezone

from sqlalchemy import Integer, DateTime, Text, Float, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column

from .database import Base


class NowcastHistory(Base):
    """Stored nowcast generated by the AI analyst."""

    __tablename__ = "nowcast_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc), index=True
    )
    valid_from: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    valid_until: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    model_used: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    details: Mapped[str] = mapped_column(Text, nullable=False)  # JSON
    confidence: Mapped[str] = mapped_column(Text, nullable=False)  # JSON
    sources_used: Mapped[str] = mapped_column(Text, nullable=False)  # JSON
    raw_response: Mapped[str] = mapped_column(Text, nullable=False)
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)


class NowcastVerification(Base):
    """Comparison of a nowcast prediction against actual observations."""

    __tablename__ = "nowcast_verification"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    nowcast_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("nowcast_history.id"), nullable=False, index=True
    )
    verified_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )
    element: Mapped[str] = mapped_column(Text, nullable=False)
    predicted: Mapped[str] = mapped_column(Text, nullable=False)
    actual: Mapped[str] = mapped_column(Text, nullable=False)
    accuracy_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class NowcastKnowledge(Base):
    """Local knowledge base entry — accumulated insights about this station's weather patterns."""

    __tablename__ = "nowcast_knowledge"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc), index=True
    )
    source: Mapped[str] = mapped_column(Text, nullable=False)  # "verification", "ai_proposed", "manual"
    category: Mapped[str] = mapped_column(Text, nullable=False)  # "bias", "timing", "terrain", "seasonal"
    content: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")  # "pending", "accepted", "rejected"
    auto_accept_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
