/**
 * AI Nowcast page — displays hyper-local short-range forecast
 * generated by Claude from station data + model guidance.
 */
import { useWeatherData } from "../context/WeatherDataContext.tsx";
import { useIsMobile } from "../hooks/useIsMobile.ts";

const cardStyle: React.CSSProperties = {
  background: "var(--color-bg-card)",
  borderRadius: "var(--gauge-border-radius)",
  border: "1px solid var(--color-border)",
  padding: "20px",
  marginBottom: "16px",
};

const sectionTitle: React.CSSProperties = {
  margin: "0 0 12px 0",
  fontSize: "16px",
  fontFamily: "var(--font-heading)",
  color: "var(--color-text)",
};

function confidenceColor(c: string): string {
  switch (c?.toUpperCase()) {
    case "HIGH":
      return "var(--color-success)";
    case "MEDIUM":
      return "var(--color-warning, #f59e0b)";
    case "LOW":
      return "var(--color-danger)";
    default:
      return "var(--color-text-muted)";
  }
}

function ConfidenceBadge({ level }: { level: string }) {
  return (
    <span
      style={{
        display: "inline-block",
        fontSize: "11px",
        fontFamily: "var(--font-body)",
        fontWeight: 600,
        padding: "2px 8px",
        borderRadius: "4px",
        background: confidenceColor(level),
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: "0.5px",
      }}
    >
      {level}
    </span>
  );
}

function timeAgo(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime();
  const minutes = Math.floor(diff / 60000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

function ElementCard({
  label,
  element,
}: {
  label: string;
  element?: { forecast: string; confidence: string; timing?: string };
}) {
  if (!element) return null;
  return (
    <div style={cardStyle}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "10px",
        }}
      >
        <h4 style={{ ...sectionTitle, margin: 0 }}>{label}</h4>
        <ConfidenceBadge level={element.confidence} />
      </div>
      <p
        style={{
          margin: 0,
          fontSize: "14px",
          fontFamily: "var(--font-body)",
          color: "var(--color-text)",
          lineHeight: 1.5,
        }}
      >
        {element.forecast}
      </p>
      {element.timing && (
        <p
          style={{
            margin: "8px 0 0 0",
            fontSize: "13px",
            fontFamily: "var(--font-mono)",
            color: "var(--color-text-secondary)",
          }}
        >
          Timing: {element.timing}
        </p>
      )}
    </div>
  );
}

export default function Nowcast() {
  const { nowcast, refreshNowcast } = useWeatherData();
  const isMobile = useIsMobile();

  if (!nowcast) {
    return (
      <div>
        <h2
          style={{
            margin: "0 0 16px 0",
            fontSize: "24px",
            fontFamily: "var(--font-heading)",
            color: "var(--color-text)",
          }}
        >
          AI Nowcast
        </h2>
        <div style={cardStyle}>
          <div
            style={{
              padding: "32px 0",
              textAlign: "center",
              color: "var(--color-text-muted)",
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              lineHeight: 1.6,
            }}
          >
            No nowcast available. Enable the AI Nowcast service in Settings
            and configure your Anthropic API key to get started.
          </div>
        </div>
      </div>
    );
  }

  const elements = nowcast.elements || {};

  return (
    <div>
      {/* Header */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "16px",
          flexWrap: "wrap",
          gap: "8px",
        }}
      >
        <h2
          style={{
            margin: 0,
            fontSize: "24px",
            fontFamily: "var(--font-heading)",
            color: "var(--color-text)",
          }}
        >
          AI Nowcast
        </h2>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "12px",
          }}
        >
          <span
            style={{
              fontSize: "12px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-muted)",
            }}
          >
            Updated {timeAgo(nowcast.created_at)}
          </span>
          <button
            onClick={refreshNowcast}
            style={{
              fontFamily: "var(--font-body)",
              fontSize: "13px",
              padding: "6px 14px",
              borderRadius: "6px",
              border: "1px solid var(--color-border)",
              background: "var(--color-bg-secondary)",
              color: "var(--color-text)",
              cursor: "pointer",
            }}
          >
            Refresh
          </button>
        </div>
      </div>

      {/* Summary */}
      <div style={{ ...cardStyle, borderLeft: "4px solid var(--color-accent)" }}>
        <p
          style={{
            margin: 0,
            fontSize: "16px",
            fontFamily: "var(--font-body)",
            color: "var(--color-text)",
            lineHeight: 1.6,
          }}
        >
          {nowcast.summary}
        </p>
      </div>

      {/* Element cards */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: isMobile
            ? "1fr"
            : "repeat(auto-fit, minmax(min(300px, 100%), 1fr))",
          gap: "0 16px",
        }}
      >
        <ElementCard label="Temperature" element={elements.temperature} />
        <ElementCard label="Precipitation" element={elements.precipitation} />
        <ElementCard label="Wind" element={elements.wind} />
        <ElementCard label="Sky Conditions" element={elements.sky} />
      </div>

      {/* Special conditions */}
      {elements.special && (
        <div
          style={{
            ...cardStyle,
            borderLeft: "4px solid var(--color-danger)",
            background: "var(--color-bg-card)",
          }}
        >
          <h4 style={{ ...sectionTitle, color: "var(--color-danger)" }}>
            Special Conditions
          </h4>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text)",
              lineHeight: 1.5,
            }}
          >
            {elements.special}
          </p>
        </div>
      )}

      {/* Farming Impact */}
      {nowcast.farming_impact && (
        <div style={cardStyle}>
          <h4 style={sectionTitle}>Farming Impact</h4>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text)",
              lineHeight: 1.5,
            }}
          >
            {nowcast.farming_impact}
          </p>
        </div>
      )}

      {/* Model Comparison */}
      {nowcast.current_vs_model && (
        <div style={cardStyle}>
          <h4 style={sectionTitle}>Observations vs. Model</h4>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              fontFamily: "var(--font-body)",
              color: "var(--color-text-secondary)",
              lineHeight: 1.5,
            }}
          >
            {nowcast.current_vs_model}
          </p>
        </div>
      )}

      {/* Footer: data quality & metadata */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "8px",
          marginTop: "8px",
          fontSize: "12px",
          fontFamily: "var(--font-body)",
          color: "var(--color-text-muted)",
        }}
      >
        <span>
          Sources: {nowcast.sources_used?.join(", ") || "local station"}
        </span>
        <span>
          Model: {nowcast.model_used} | Tokens: {nowcast.input_tokens}
          /{nowcast.output_tokens}
        </span>
      </div>
    </div>
  );
}
